env: "dev" # local, dev, prod
storage_name: "url-shortener"
storage_path: "mongodb://admin:password@mongo_c:27017"
http_server:
  address: "0.0.0.0:8080"
  user : "myuser"
  password: "mypass"
  idle_timeout: 60s
  timeout: 1000s #time to receive request and respond to it
