env: "local" # local, dev, prod
storage_name: "url-shortener"
storage_path: "mongodb://localhost:27017"
http_server:
  address: "localhost:8082"
  user : "myuser"
  password: "mypassword"
  idle_timeout: 60s
  timeout: 1000s #time to receive request and respond to it
